In [22]:
import numpy as np
import pandas as pd

###*Работа с Numpy*

###Задание 1 

In [20]:
a = np.array([[1, 6],
              [2, 8],
              [3, 11],
              [3, 10],
              [1, 7]])
print(a)

[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]


In [19]:
mean_a = a.mean(axis=0)
mean_a

array([2. , 8.4])

###Задание 2

In [18]:
a_centered = np.subtract(a, mean_a)
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

###Задание 3 

In [17]:
a_1 = a_centered[: , 0]
a_2 = a_centered[: , 1]
a_centered_sp = np.dot(a_1, a_2)
a_centered_sp

8.0

In [21]:
N = a.shape[0]
res = a_centered_sp/(N-1)
res

2.0

###*Работа с Pandas*

### Задание 1 


In [23]:
authors = pd.DataFrame({'author_id':[1, 2, 3],

'author_name':['Тургенев', 'Чехов', 'Островский']}, columns=['author_id', 'author_name'])

authors 

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [24]:
book = pd.DataFrame({'author_id':[1, 1, 1, 2, 2, 3, 3],

'book_title':['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],

'price':[450, 300, 350, 500, 450, 370, 290]},

columns=['author_id', 'book_title', 'price'])

book

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

### Задание 2 

In [26]:
authors_price = pd.merge(authors, book, on = 'author_id', how = 'outer')

authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

### Задание 3


In [27]:
max_price5 = authors_price.nlargest(5, 'price')

max_price5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

### Задание 4

In [28]:
d_frame1 = authors_price.groupby('author_name').agg({'price': 'min'}).rename(columns={'price':'min_price'})

d_frame2 = authors_price.groupby('author_name').agg({'price': 'max'}).rename(columns={'price':'max_price'})

d_frame3 = authors_price.groupby('author_name').agg({'price': 'mean'}).rename(columns={'price':'mean_price'})

authors_info = pd.concat([d_frame1, d_frame2, d_frame3], axis = 1)

authors_info 

min_price  max_price  mean_price
author_name                                  
Островский         290        370  330.000000
Тургенев           300        450  366.666667
Чехов              450        500  475.000000